### ISSUE TITLE
Bug Report:  i cant compile the game 

### ISSUE THREAD

**Issue by ghost** [Lexicord/ccbossrush-master#3]
i have the same error as the other guy and when i did it it gave me more errors please fix it iv'e gone mad trying to fix it  
here are the errors 

source/PlayState.hx:3369: characters 8-26 : Unknown identifier : currentTimingShown
source/PlayState.hx:3372: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3373: characters 4-13 : Unknown identifier : timeShown
source/PlayState.hx:3377: characters 6-24 : Unknown identifier : currentTimingShown
source/PlayState.hx:3379: characters 6-24 : Unknown identifier : currentTimingShown
source/PlayState.hx:3381: characters 6-24 : Unknown identifier : currentTimingShown
source/PlayState.hx:3383: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3384: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3385: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3386: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3387: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3392: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3393: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3394: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3395: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3396: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3397: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3398: characters 5-9 : Unknown identifier : hits
source/PlayState.hx:3402: characters 14-18 : Unknown identifier : hits
source/PlayState.hx:3407: characters 5-15 : Unknown identifier : offsetTest
source/PlayState.hx:3410: characters 8-26 : Unknown identifier : currentTimingShown
source/PlayState.hx:3413: characters 53-71 : Unknown identifier : currentTimingShown
source/PlayState.hx:3413: characters 53-71 : For function argument 'Object'
source/PlayState.hx:3422: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3423: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3424: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3425: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3426: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3429: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3445: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3449: characters 4-22 : Unknown identifier : currentTimingShown
source/PlayState.hx:3523: characters 10-28 : Unknown identifier : currentTimingShown
source/PlayState.hx:3525: characters 6-15 : Unknown identifier : timeShown
source/PlayState.hx:3534: characters 10-28 : Unknown identifier : currentTimingShown
source/AchievementState.hx:13: characters 8-15 : Module Discord does not define type Discord
source/SkinState.hx:13: characters 8-15 : Module Discord does not define type Discord
source/PlayState.hx:1808: characters 33-40 : Unknown identifier : endSong
source/PlayState.hx:3028: characters 4-11 : Unknown identifier : endSong
source/PlayState.hx:3093: characters 28-38 : Unknown identifier : offsetTest 

please fix this

**Comment by Lexicord** [comment]
lol

**Comment by ghost** [comment]
plz fix it

**Comment by ghost** [comment]
im trying to make your mod a mac version

**Comment by Lexicord** [comment]
no lol i didn't give you permission to make a mac port 💀💀💀
